// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/chain_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 健康检查
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取余额
type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetBalanceResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetBalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBalanceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 转账
type TransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{4}
}

func (x *TransferRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *TransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type TransferResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash string                 `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Success         bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransferResponse) Reset() {
	*x = TransferResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferResponse) ProtoMessage() {}

func (x *TransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferResponse.ProtoReflect.Descriptor instead.
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{5}
}

func (x *TransferResponse) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *TransferResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TransferResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 获取交易
type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,5,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	GasPrice      string                 `protobuf:"bytes,6,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Success       bool                   `protobuf:"varint,9,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GetTransactionResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GetTransactionResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GetTransactionResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetTransactionResponse) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *GetTransactionResponse) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *GetTransactionResponse) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetTransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 调用合约
type CallContractRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Method          string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params          []string               `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CallContractRequest) Reset() {
	*x = CallContractRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractRequest) ProtoMessage() {}

func (x *CallContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractRequest.ProtoReflect.Descriptor instead.
func (*CallContractRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{8}
}

func (x *CallContractRequest) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *CallContractRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallContractRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type CallContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallContractResponse) Reset() {
	*x = CallContractResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallContractResponse) ProtoMessage() {}

func (x *CallContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallContractResponse.ProtoReflect.Descriptor instead.
func (*CallContractResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{9}
}

func (x *CallContractResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *CallContractResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallContractResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 部署合约
type DeployContractRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Bytecode          string                 `protobuf:"bytes,1,opt,name=bytecode,proto3" json:"bytecode,omitempty"`
	ConstructorParams []string               `protobuf:"bytes,2,rep,name=constructor_params,json=constructorParams,proto3" json:"constructor_params,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeployContractRequest) Reset() {
	*x = DeployContractRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployContractRequest) ProtoMessage() {}

func (x *DeployContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployContractRequest.ProtoReflect.Descriptor instead.
func (*DeployContractRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeployContractRequest) GetBytecode() string {
	if x != nil {
		return x.Bytecode
	}
	return ""
}

func (x *DeployContractRequest) GetConstructorParams() []string {
	if x != nil {
		return x.ConstructorParams
	}
	return nil
}

type DeployContractResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractAddress string                 `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	TransactionHash string                 `protobuf:"bytes,2,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	Success         bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeployContractResponse) Reset() {
	*x = DeployContractResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployContractResponse) ProtoMessage() {}

func (x *DeployContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployContractResponse.ProtoReflect.Descriptor instead.
func (*DeployContractResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeployContractResponse) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *DeployContractResponse) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *DeployContractResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeployContractResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BSC代币信息
type GetTokenInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenInfoRequest) Reset() {
	*x = GetTokenInfoRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoRequest) ProtoMessage() {}

func (x *GetTokenInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTokenInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetTokenInfoRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      uint32                 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	TotalSupply   string                 `protobuf:"bytes,5,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_proto_chain_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{13}
}

func (x *TokenInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokenInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenInfo) GetTotalSupply() string {
	if x != nil {
		return x.TotalSupply
	}
	return ""
}

type GetTokenInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *TokenInfo             `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenInfoResponse) Reset() {
	*x = GetTokenInfoResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoResponse) ProtoMessage() {}

func (x *GetTokenInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoResponse.ProtoReflect.Descriptor instead.
func (*GetTokenInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetTokenInfoResponse) GetToken() *TokenInfo {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *GetTokenInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTokenInfoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 搜索代币
type SearchTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTokenRequest) Reset() {
	*x = SearchTokenRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTokenRequest) ProtoMessage() {}

func (x *SearchTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTokenRequest.ProtoReflect.Descriptor instead.
func (*SearchTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{15}
}

func (x *SearchTokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenInfo           `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTokenResponse) Reset() {
	*x = SearchTokenResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTokenResponse) ProtoMessage() {}

func (x *SearchTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTokenResponse.ProtoReflect.Descriptor instead.
func (*SearchTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{16}
}

func (x *SearchTokenResponse) GetTokens() []*TokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *SearchTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchTokenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 获取代币价格
type GetTokenPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	TokenName     string                 `protobuf:"bytes,2,opt,name=token_name,json=tokenName,proto3" json:"token_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPriceRequest) Reset() {
	*x = GetTokenPriceRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPriceRequest) ProtoMessage() {}

func (x *GetTokenPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPriceRequest.ProtoReflect.Descriptor instead.
func (*GetTokenPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetTokenPriceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetTokenPriceRequest) GetTokenName() string {
	if x != nil {
		return x.TokenName
	}
	return ""
}

type TokenPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PriceUsd      string                 `protobuf:"bytes,4,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	PriceBnb      string                 `protobuf:"bytes,5,opt,name=price_bnb,json=priceBnb,proto3" json:"price_bnb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPrice) Reset() {
	*x = TokenPrice{}
	mi := &file_proto_chain_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPrice) ProtoMessage() {}

func (x *TokenPrice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPrice.ProtoReflect.Descriptor instead.
func (*TokenPrice) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{18}
}

func (x *TokenPrice) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokenPrice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenPrice) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenPrice) GetPriceUsd() string {
	if x != nil {
		return x.PriceUsd
	}
	return ""
}

func (x *TokenPrice) GetPriceBnb() string {
	if x != nil {
		return x.PriceBnb
	}
	return ""
}

type GetTokenPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *TokenPrice            `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenPriceResponse) Reset() {
	*x = GetTokenPriceResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenPriceResponse) ProtoMessage() {}

func (x *GetTokenPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenPriceResponse.ProtoReflect.Descriptor instead.
func (*GetTokenPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetTokenPriceResponse) GetPrice() *TokenPrice {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *GetTokenPriceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTokenPriceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 批量获取代币价格
type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{20}
}

func (x *TokenRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokenRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMultipleTokenPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*TokenRequest        `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleTokenPricesRequest) Reset() {
	*x = GetMultipleTokenPricesRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleTokenPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleTokenPricesRequest) ProtoMessage() {}

func (x *GetMultipleTokenPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleTokenPricesRequest.ProtoReflect.Descriptor instead.
func (*GetMultipleTokenPricesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetMultipleTokenPricesRequest) GetTokens() []*TokenRequest {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type GetMultipleTokenPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*TokenPrice          `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleTokenPricesResponse) Reset() {
	*x = GetMultipleTokenPricesResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleTokenPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleTokenPricesResponse) ProtoMessage() {}

func (x *GetMultipleTokenPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleTokenPricesResponse.ProtoReflect.Descriptor instead.
func (*GetMultipleTokenPricesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetMultipleTokenPricesResponse) GetPrices() []*TokenPrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *GetMultipleTokenPricesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMultipleTokenPricesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// 获取流动性池
type GetLiquidityPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token0        string                 `protobuf:"bytes,1,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1        string                 `protobuf:"bytes,2,opt,name=token1,proto3" json:"token1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiquidityPoolRequest) Reset() {
	*x = GetLiquidityPoolRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiquidityPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiquidityPoolRequest) ProtoMessage() {}

func (x *GetLiquidityPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiquidityPoolRequest.ProtoReflect.Descriptor instead.
func (*GetLiquidityPoolRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetLiquidityPoolRequest) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *GetLiquidityPoolRequest) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

type LiquidityPool struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PairAddress    string                 `protobuf:"bytes,1,opt,name=pair_address,json=pairAddress,proto3" json:"pair_address,omitempty"`
	Token0         string                 `protobuf:"bytes,2,opt,name=token0,proto3" json:"token0,omitempty"`
	Token1         string                 `protobuf:"bytes,3,opt,name=token1,proto3" json:"token1,omitempty"`
	TotalLiquidity string                 `protobuf:"bytes,4,opt,name=total_liquidity,json=totalLiquidity,proto3" json:"total_liquidity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LiquidityPool) Reset() {
	*x = LiquidityPool{}
	mi := &file_proto_chain_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiquidityPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiquidityPool) ProtoMessage() {}

func (x *LiquidityPool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiquidityPool.ProtoReflect.Descriptor instead.
func (*LiquidityPool) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{24}
}

func (x *LiquidityPool) GetPairAddress() string {
	if x != nil {
		return x.PairAddress
	}
	return ""
}

func (x *LiquidityPool) GetToken0() string {
	if x != nil {
		return x.Token0
	}
	return ""
}

func (x *LiquidityPool) GetToken1() string {
	if x != nil {
		return x.Token1
	}
	return ""
}

func (x *LiquidityPool) GetTotalLiquidity() string {
	if x != nil {
		return x.TotalLiquidity
	}
	return ""
}

// 价格服务消息
type CryptoPriceInfo struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Symbol                 string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CurrentPrice           float64                `protobuf:"fixed64,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	MarketCap              float64                `protobuf:"fixed64,4,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	Volume_24H             float64                `protobuf:"fixed64,5,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	PriceChange_24H        float64                `protobuf:"fixed64,6,opt,name=price_change_24h,json=priceChange24h,proto3" json:"price_change_24h,omitempty"`
	PriceChangePercent_24H float64                `protobuf:"fixed64,7,opt,name=price_change_percent_24h,json=priceChangePercent24h,proto3" json:"price_change_percent_24h,omitempty"`
	LastUpdated            string                 `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CryptoPriceInfo) Reset() {
	*x = CryptoPriceInfo{}
	mi := &file_proto_chain_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoPriceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoPriceInfo) ProtoMessage() {}

func (x *CryptoPriceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoPriceInfo.ProtoReflect.Descriptor instead.
func (*CryptoPriceInfo) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{25}
}

func (x *CryptoPriceInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CryptoPriceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CryptoPriceInfo) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *CryptoPriceInfo) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *CryptoPriceInfo) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *CryptoPriceInfo) GetPriceChange_24H() float64 {
	if x != nil {
		return x.PriceChange_24H
	}
	return 0
}

func (x *CryptoPriceInfo) GetPriceChangePercent_24H() float64 {
	if x != nil {
		return x.PriceChangePercent_24H
	}
	return 0
}

func (x *CryptoPriceInfo) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type GetCryptoPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCryptoPriceRequest) Reset() {
	*x = GetCryptoPriceRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCryptoPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoPriceRequest) ProtoMessage() {}

func (x *GetCryptoPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoPriceRequest.ProtoReflect.Descriptor instead.
func (*GetCryptoPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetCryptoPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetCryptoPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Price         *CryptoPriceInfo       `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCryptoPriceResponse) Reset() {
	*x = GetCryptoPriceResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCryptoPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCryptoPriceResponse) ProtoMessage() {}

func (x *GetCryptoPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCryptoPriceResponse.ProtoReflect.Descriptor instead.
func (*GetCryptoPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{27}
}

func (x *GetCryptoPriceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCryptoPriceResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetCryptoPriceResponse) GetPrice() *CryptoPriceInfo {
	if x != nil {
		return x.Price
	}
	return nil
}

type GetMultipleCryptoPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleCryptoPricesRequest) Reset() {
	*x = GetMultipleCryptoPricesRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleCryptoPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleCryptoPricesRequest) ProtoMessage() {}

func (x *GetMultipleCryptoPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleCryptoPricesRequest.ProtoReflect.Descriptor instead.
func (*GetMultipleCryptoPricesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{28}
}

func (x *GetMultipleCryptoPricesRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetMultipleCryptoPricesResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Success       bool                        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                      `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Prices        map[string]*CryptoPriceInfo `protobuf:"bytes,3,rep,name=prices,proto3" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleCryptoPricesResponse) Reset() {
	*x = GetMultipleCryptoPricesResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleCryptoPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleCryptoPricesResponse) ProtoMessage() {}

func (x *GetMultipleCryptoPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleCryptoPricesResponse.ProtoReflect.Descriptor instead.
func (*GetMultipleCryptoPricesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{29}
}

func (x *GetMultipleCryptoPricesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetMultipleCryptoPricesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetMultipleCryptoPricesResponse) GetPrices() map[string]*CryptoPriceInfo {
	if x != nil {
		return x.Prices
	}
	return nil
}

type GetTopCryptoPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopCryptoPricesRequest) Reset() {
	*x = GetTopCryptoPricesRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopCryptoPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopCryptoPricesRequest) ProtoMessage() {}

func (x *GetTopCryptoPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopCryptoPricesRequest.ProtoReflect.Descriptor instead.
func (*GetTopCryptoPricesRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{30}
}

func (x *GetTopCryptoPricesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopCryptoPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Prices        []*CryptoPriceInfo     `protobuf:"bytes,3,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopCryptoPricesResponse) Reset() {
	*x = GetTopCryptoPricesResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopCryptoPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopCryptoPricesResponse) ProtoMessage() {}

func (x *GetTopCryptoPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopCryptoPricesResponse.ProtoReflect.Descriptor instead.
func (*GetTopCryptoPricesResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{31}
}

func (x *GetTopCryptoPricesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTopCryptoPricesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTopCryptoPricesResponse) GetPrices() []*CryptoPriceInfo {
	if x != nil {
		return x.Prices
	}
	return nil
}

type SearchCryptoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCryptoRequest) Reset() {
	*x = SearchCryptoRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCryptoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCryptoRequest) ProtoMessage() {}

func (x *SearchCryptoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCryptoRequest.ProtoReflect.Descriptor instead.
func (*SearchCryptoRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{32}
}

func (x *SearchCryptoRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchCryptoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Results       []*CryptoPriceInfo     `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCryptoResponse) Reset() {
	*x = SearchCryptoResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCryptoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCryptoResponse) ProtoMessage() {}

func (x *SearchCryptoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCryptoResponse.ProtoReflect.Descriptor instead.
func (*SearchCryptoResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{33}
}

func (x *SearchCryptoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchCryptoResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SearchCryptoResponse) GetResults() []*CryptoPriceInfo {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetPriceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceHistoryRequest) Reset() {
	*x = GetPriceHistoryRequest{}
	mi := &file_proto_chain_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceHistoryRequest) ProtoMessage() {}

func (x *GetPriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{34}
}

func (x *GetPriceHistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetPriceHistoryRequest) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetPriceHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Prices        []float64              `protobuf:"fixed64,3,rep,packed,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceHistoryResponse) Reset() {
	*x = GetPriceHistoryResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceHistoryResponse) ProtoMessage() {}

func (x *GetPriceHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetPriceHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{35}
}

func (x *GetPriceHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPriceHistoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetPriceHistoryResponse) GetPrices() []float64 {
	if x != nil {
		return x.Prices
	}
	return nil
}

type GetLiquidityPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *LiquidityPool         `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiquidityPoolResponse) Reset() {
	*x = GetLiquidityPoolResponse{}
	mi := &file_proto_chain_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiquidityPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiquidityPoolResponse) ProtoMessage() {}

func (x *GetLiquidityPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chain_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiquidityPoolResponse.ProtoReflect.Descriptor instead.
func (*GetLiquidityPoolResponse) Descriptor() ([]byte, []int) {
	return file_proto_chain_service_proto_rawDescGZIP(), []int{36}
}

func (x *GetLiquidityPoolResponse) GetPool() *LiquidityPool {
	if x != nil {
		return x.Pool
	}
	return nil
}

func (x *GetLiquidityPoolResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetLiquidityPoolResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_chain_service_proto protoreflect.FileDescriptor

const file_proto_chain_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/chain_service.proto\x12\x05chain\"\x14\n" +
	"\x12HealthCheckRequest\"G\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"-\n" +
	"\x11GetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"x\n" +
	"\x12GetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"9\n" +
	"\x0fTransferRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"m\n" +
	"\x10TransferResponse\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHash\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"+\n" +
	"\x15GetTransactionRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"\x89\x02\n" +
	"\x16GetTransactionResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x19\n" +
	"\bgas_used\x18\x05 \x01(\x04R\agasUsed\x12\x1b\n" +
	"\tgas_price\x18\x06 \x01(\tR\bgasPrice\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x18\n" +
	"\asuccess\x18\t \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"p\n" +
	"\x13CallContractRequest\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06params\x18\x03 \x03(\tR\x06params\"^\n" +
	"\x14CallContractResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"b\n" +
	"\x15DeployContractRequest\x12\x1a\n" +
	"\bbytecode\x18\x01 \x01(\tR\bbytecode\x12-\n" +
	"\x12constructor_params\x18\x02 \x03(\tR\x11constructorParams\"\x9e\x01\n" +
	"\x16DeployContractResponse\x12)\n" +
	"\x10contract_address\x18\x01 \x01(\tR\x0fcontractAddress\x12)\n" +
	"\x10transaction_hash\x18\x02 \x01(\tR\x0ftransactionHash\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"/\n" +
	"\x13GetTokenInfoRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x90\x01\n" +
	"\tTokenInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimals\x12!\n" +
	"\ftotal_supply\x18\x05 \x01(\tR\vtotalSupply\"n\n" +
	"\x14GetTokenInfoResponse\x12&\n" +
	"\x05token\x18\x01 \x01(\v2\x10.chain.TokenInfoR\x05token\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"(\n" +
	"\x12SearchTokenRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"o\n" +
	"\x13SearchTokenResponse\x12(\n" +
	"\x06tokens\x18\x01 \x03(\v2\x10.chain.TokenInfoR\x06tokens\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"O\n" +
	"\x14GetTokenPriceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"token_name\x18\x02 \x01(\tR\ttokenName\"\x8c\x01\n" +
	"\n" +
	"TokenPrice\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x1b\n" +
	"\tprice_usd\x18\x04 \x01(\tR\bpriceUsd\x12\x1b\n" +
	"\tprice_bnb\x18\x05 \x01(\tR\bpriceBnb\"p\n" +
	"\x15GetTokenPriceResponse\x12'\n" +
	"\x05price\x18\x01 \x01(\v2\x11.chain.TokenPriceR\x05price\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"<\n" +
	"\fTokenRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"L\n" +
	"\x1dGetMultipleTokenPricesRequest\x12+\n" +
	"\x06tokens\x18\x01 \x03(\v2\x13.chain.TokenRequestR\x06tokens\"{\n" +
	"\x1eGetMultipleTokenPricesResponse\x12)\n" +
	"\x06prices\x18\x01 \x03(\v2\x11.chain.TokenPriceR\x06prices\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"I\n" +
	"\x17GetLiquidityPoolRequest\x12\x16\n" +
	"\x06token0\x18\x01 \x01(\tR\x06token0\x12\x16\n" +
	"\x06token1\x18\x02 \x01(\tR\x06token1\"\x8b\x01\n" +
	"\rLiquidityPool\x12!\n" +
	"\fpair_address\x18\x01 \x01(\tR\vpairAddress\x12\x16\n" +
	"\x06token0\x18\x02 \x01(\tR\x06token0\x12\x16\n" +
	"\x06token1\x18\x03 \x01(\tR\x06token1\x12'\n" +
	"\x0ftotal_liquidity\x18\x04 \x01(\tR\x0etotalLiquidity\"\xa6\x02\n" +
	"\x0fCryptoPriceInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x01R\fcurrentPrice\x12\x1d\n" +
	"\n" +
	"market_cap\x18\x04 \x01(\x01R\tmarketCap\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\x05 \x01(\x01R\tvolume24h\x12(\n" +
	"\x10price_change_24h\x18\x06 \x01(\x01R\x0epriceChange24h\x127\n" +
	"\x18price_change_percent_24h\x18\a \x01(\x01R\x15priceChangePercent24h\x12!\n" +
	"\flast_updated\x18\b \x01(\tR\vlastUpdated\"/\n" +
	"\x15GetCryptoPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"v\n" +
	"\x16GetCryptoPriceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12,\n" +
	"\x05price\x18\x03 \x01(\v2\x16.chain.CryptoPriceInfoR\x05price\":\n" +
	"\x1eGetMultipleCryptoPricesRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\xf0\x01\n" +
	"\x1fGetMultipleCryptoPricesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12J\n" +
	"\x06prices\x18\x03 \x03(\v22.chain.GetMultipleCryptoPricesResponse.PricesEntryR\x06prices\x1aQ\n" +
	"\vPricesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.chain.CryptoPriceInfoR\x05value:\x028\x01\"1\n" +
	"\x19GetTopCryptoPricesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"|\n" +
	"\x1aGetTopCryptoPricesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\x06prices\x18\x03 \x03(\v2\x16.chain.CryptoPriceInfoR\x06prices\"+\n" +
	"\x13SearchCryptoRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"x\n" +
	"\x14SearchCryptoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\aresults\x18\x03 \x03(\v2\x16.chain.CryptoPriceInfoR\aresults\"D\n" +
	"\x16GetPriceHistoryRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\"a\n" +
	"\x17GetPriceHistoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x16\n" +
	"\x06prices\x18\x03 \x03(\x01R\x06prices\"t\n" +
	"\x18GetLiquidityPoolResponse\x12(\n" +
	"\x04pool\x18\x01 \x01(\v2\x14.chain.LiquidityPoolR\x04pool\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xf5\x02\n" +
	"\fChainService\x12A\n" +
	"\n" +
	"GetBalance\x12\x18.chain.GetBalanceRequest\x1a\x19.chain.GetBalanceResponse\x12;\n" +
	"\bTransfer\x12\x16.chain.TransferRequest\x1a\x17.chain.TransferResponse\x12M\n" +
	"\x0eGetTransaction\x12\x1c.chain.GetTransactionRequest\x1a\x1d.chain.GetTransactionResponse\x12G\n" +
	"\fCallContract\x12\x1a.chain.CallContractRequest\x1a\x1b.chain.CallContractResponse\x12M\n" +
	"\x0eDeployContract\x12\x1c.chain.DeployContractRequest\x1a\x1d.chain.DeployContractResponse2\xa3\x03\n" +
	"\n" +
	"BSCService\x12G\n" +
	"\fGetTokenInfo\x12\x1a.chain.GetTokenInfoRequest\x1a\x1b.chain.GetTokenInfoResponse\x12D\n" +
	"\vSearchToken\x12\x19.chain.SearchTokenRequest\x1a\x1a.chain.SearchTokenResponse\x12J\n" +
	"\rGetTokenPrice\x12\x1b.chain.GetTokenPriceRequest\x1a\x1c.chain.GetTokenPriceResponse\x12e\n" +
	"\x16GetMultipleTokenPrices\x12$.chain.GetMultipleTokenPricesRequest\x1a%.chain.GetMultipleTokenPricesResponse\x12S\n" +
	"\x10GetLiquidityPool\x12\x1e.chain.GetLiquidityPoolRequest\x1a\x1f.chain.GetLiquidityPoolResponse2O\n" +
	"\rHealthService\x12>\n" +
	"\x05Check\x12\x19.chain.HealthCheckRequest\x1a\x1a.chain.HealthCheckResponse2\xbd\x03\n" +
	"\fPriceService\x12M\n" +
	"\x0eGetCryptoPrice\x12\x1c.chain.GetCryptoPriceRequest\x1a\x1d.chain.GetCryptoPriceResponse\x12h\n" +
	"\x17GetMultipleCryptoPrices\x12%.chain.GetMultipleCryptoPricesRequest\x1a&.chain.GetMultipleCryptoPricesResponse\x12Y\n" +
	"\x12GetTopCryptoPrices\x12 .chain.GetTopCryptoPricesRequest\x1a!.chain.GetTopCryptoPricesResponse\x12G\n" +
	"\fSearchCrypto\x12\x1a.chain.SearchCryptoRequest\x1a\x1b.chain.SearchCryptoResponse\x12P\n" +
	"\x0fGetPriceHistory\x12\x1d.chain.GetPriceHistoryRequest\x1a\x1e.chain.GetPriceHistoryResponseB\rZ\vchain/protob\x06proto3"

var (
	file_proto_chain_service_proto_rawDescOnce sync.Once
	file_proto_chain_service_proto_rawDescData []byte
)

func file_proto_chain_service_proto_rawDescGZIP() []byte {
	file_proto_chain_service_proto_rawDescOnce.Do(func() {
		file_proto_chain_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chain_service_proto_rawDesc), len(file_proto_chain_service_proto_rawDesc)))
	})
	return file_proto_chain_service_proto_rawDescData
}

var file_proto_chain_service_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_proto_chain_service_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),              // 0: chain.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 1: chain.HealthCheckResponse
	(*GetBalanceRequest)(nil),               // 2: chain.GetBalanceRequest
	(*GetBalanceResponse)(nil),              // 3: chain.GetBalanceResponse
	(*TransferRequest)(nil),                 // 4: chain.TransferRequest
	(*TransferResponse)(nil),                // 5: chain.TransferResponse
	(*GetTransactionRequest)(nil),           // 6: chain.GetTransactionRequest
	(*GetTransactionResponse)(nil),          // 7: chain.GetTransactionResponse
	(*CallContractRequest)(nil),             // 8: chain.CallContractRequest
	(*CallContractResponse)(nil),            // 9: chain.CallContractResponse
	(*DeployContractRequest)(nil),           // 10: chain.DeployContractRequest
	(*DeployContractResponse)(nil),          // 11: chain.DeployContractResponse
	(*GetTokenInfoRequest)(nil),             // 12: chain.GetTokenInfoRequest
	(*TokenInfo)(nil),                       // 13: chain.TokenInfo
	(*GetTokenInfoResponse)(nil),            // 14: chain.GetTokenInfoResponse
	(*SearchTokenRequest)(nil),              // 15: chain.SearchTokenRequest
	(*SearchTokenResponse)(nil),             // 16: chain.SearchTokenResponse
	(*GetTokenPriceRequest)(nil),            // 17: chain.GetTokenPriceRequest
	(*TokenPrice)(nil),                      // 18: chain.TokenPrice
	(*GetTokenPriceResponse)(nil),           // 19: chain.GetTokenPriceResponse
	(*TokenRequest)(nil),                    // 20: chain.TokenRequest
	(*GetMultipleTokenPricesRequest)(nil),   // 21: chain.GetMultipleTokenPricesRequest
	(*GetMultipleTokenPricesResponse)(nil),  // 22: chain.GetMultipleTokenPricesResponse
	(*GetLiquidityPoolRequest)(nil),         // 23: chain.GetLiquidityPoolRequest
	(*LiquidityPool)(nil),                   // 24: chain.LiquidityPool
	(*CryptoPriceInfo)(nil),                 // 25: chain.CryptoPriceInfo
	(*GetCryptoPriceRequest)(nil),           // 26: chain.GetCryptoPriceRequest
	(*GetCryptoPriceResponse)(nil),          // 27: chain.GetCryptoPriceResponse
	(*GetMultipleCryptoPricesRequest)(nil),  // 28: chain.GetMultipleCryptoPricesRequest
	(*GetMultipleCryptoPricesResponse)(nil), // 29: chain.GetMultipleCryptoPricesResponse
	(*GetTopCryptoPricesRequest)(nil),       // 30: chain.GetTopCryptoPricesRequest
	(*GetTopCryptoPricesResponse)(nil),      // 31: chain.GetTopCryptoPricesResponse
	(*SearchCryptoRequest)(nil),             // 32: chain.SearchCryptoRequest
	(*SearchCryptoResponse)(nil),            // 33: chain.SearchCryptoResponse
	(*GetPriceHistoryRequest)(nil),          // 34: chain.GetPriceHistoryRequest
	(*GetPriceHistoryResponse)(nil),         // 35: chain.GetPriceHistoryResponse
	(*GetLiquidityPoolResponse)(nil),        // 36: chain.GetLiquidityPoolResponse
	nil,                                     // 37: chain.GetMultipleCryptoPricesResponse.PricesEntry
}
var file_proto_chain_service_proto_depIdxs = []int32{
	13, // 0: chain.GetTokenInfoResponse.token:type_name -> chain.TokenInfo
	13, // 1: chain.SearchTokenResponse.tokens:type_name -> chain.TokenInfo
	18, // 2: chain.GetTokenPriceResponse.price:type_name -> chain.TokenPrice
	20, // 3: chain.GetMultipleTokenPricesRequest.tokens:type_name -> chain.TokenRequest
	18, // 4: chain.GetMultipleTokenPricesResponse.prices:type_name -> chain.TokenPrice
	25, // 5: chain.GetCryptoPriceResponse.price:type_name -> chain.CryptoPriceInfo
	37, // 6: chain.GetMultipleCryptoPricesResponse.prices:type_name -> chain.GetMultipleCryptoPricesResponse.PricesEntry
	25, // 7: chain.GetTopCryptoPricesResponse.prices:type_name -> chain.CryptoPriceInfo
	25, // 8: chain.SearchCryptoResponse.results:type_name -> chain.CryptoPriceInfo
	24, // 9: chain.GetLiquidityPoolResponse.pool:type_name -> chain.LiquidityPool
	25, // 10: chain.GetMultipleCryptoPricesResponse.PricesEntry.value:type_name -> chain.CryptoPriceInfo
	2,  // 11: chain.ChainService.GetBalance:input_type -> chain.GetBalanceRequest
	4,  // 12: chain.ChainService.Transfer:input_type -> chain.TransferRequest
	6,  // 13: chain.ChainService.GetTransaction:input_type -> chain.GetTransactionRequest
	8,  // 14: chain.ChainService.CallContract:input_type -> chain.CallContractRequest
	10, // 15: chain.ChainService.DeployContract:input_type -> chain.DeployContractRequest
	12, // 16: chain.BSCService.GetTokenInfo:input_type -> chain.GetTokenInfoRequest
	15, // 17: chain.BSCService.SearchToken:input_type -> chain.SearchTokenRequest
	17, // 18: chain.BSCService.GetTokenPrice:input_type -> chain.GetTokenPriceRequest
	21, // 19: chain.BSCService.GetMultipleTokenPrices:input_type -> chain.GetMultipleTokenPricesRequest
	23, // 20: chain.BSCService.GetLiquidityPool:input_type -> chain.GetLiquidityPoolRequest
	0,  // 21: chain.HealthService.Check:input_type -> chain.HealthCheckRequest
	26, // 22: chain.PriceService.GetCryptoPrice:input_type -> chain.GetCryptoPriceRequest
	28, // 23: chain.PriceService.GetMultipleCryptoPrices:input_type -> chain.GetMultipleCryptoPricesRequest
	30, // 24: chain.PriceService.GetTopCryptoPrices:input_type -> chain.GetTopCryptoPricesRequest
	32, // 25: chain.PriceService.SearchCrypto:input_type -> chain.SearchCryptoRequest
	34, // 26: chain.PriceService.GetPriceHistory:input_type -> chain.GetPriceHistoryRequest
	3,  // 27: chain.ChainService.GetBalance:output_type -> chain.GetBalanceResponse
	5,  // 28: chain.ChainService.Transfer:output_type -> chain.TransferResponse
	7,  // 29: chain.ChainService.GetTransaction:output_type -> chain.GetTransactionResponse
	9,  // 30: chain.ChainService.CallContract:output_type -> chain.CallContractResponse
	11, // 31: chain.ChainService.DeployContract:output_type -> chain.DeployContractResponse
	14, // 32: chain.BSCService.GetTokenInfo:output_type -> chain.GetTokenInfoResponse
	16, // 33: chain.BSCService.SearchToken:output_type -> chain.SearchTokenResponse
	19, // 34: chain.BSCService.GetTokenPrice:output_type -> chain.GetTokenPriceResponse
	22, // 35: chain.BSCService.GetMultipleTokenPrices:output_type -> chain.GetMultipleTokenPricesResponse
	36, // 36: chain.BSCService.GetLiquidityPool:output_type -> chain.GetLiquidityPoolResponse
	1,  // 37: chain.HealthService.Check:output_type -> chain.HealthCheckResponse
	27, // 38: chain.PriceService.GetCryptoPrice:output_type -> chain.GetCryptoPriceResponse
	29, // 39: chain.PriceService.GetMultipleCryptoPrices:output_type -> chain.GetMultipleCryptoPricesResponse
	31, // 40: chain.PriceService.GetTopCryptoPrices:output_type -> chain.GetTopCryptoPricesResponse
	33, // 41: chain.PriceService.SearchCrypto:output_type -> chain.SearchCryptoResponse
	35, // 42: chain.PriceService.GetPriceHistory:output_type -> chain.GetPriceHistoryResponse
	27, // [27:43] is the sub-list for method output_type
	11, // [11:27] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_chain_service_proto_init() }
func file_proto_chain_service_proto_init() {
	if File_proto_chain_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chain_service_proto_rawDesc), len(file_proto_chain_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_chain_service_proto_goTypes,
		DependencyIndexes: file_proto_chain_service_proto_depIdxs,
		MessageInfos:      file_proto_chain_service_proto_msgTypes,
	}.Build()
	File_proto_chain_service_proto = out.File
	file_proto_chain_service_proto_goTypes = nil
	file_proto_chain_service_proto_depIdxs = nil
}
