server:
  port: "8080"
  grpc_port: "9090"
  host: "0.0.0.0"

chain:
  rpc_url: "https://bsc-dataseed1.binance.org/"
  private_key: "0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
  chain_id: 56
  gas_limit: 21000

database:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "password"
  dbname: "chain"
  driver: "mysql"

registry:
  type: "etcd"  # 支持 etcd, consul, memory
  endpoints: "localhost:2379"  # etcd地址，多个用逗号分隔

log_level: "info"